services:
  - type: web
    name: fastatoms
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:////var/data/fastatoms.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: FRONTEND_DIST
        value: /app/frontend/dist
      - key: ENVIRONMENT
        value: prod
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
